[package]
name = "vehicle-net"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]
description = "A simple project with Rust and Web components"

[[bin]]
name = "hello-world"
path = "rust/src/main.rs"

[dependencies]
# No dependencies needed for hello world