name: Integration Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Foundry (nightly)
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          ~/.foundry/bin/foundryup

      - name: Create output directory
        run: mkdir -p scripts/output

      - name: Run integration tests
        run: |
          set -e
          chmod +x scripts/test-integration.sh || true
          ./scripts/test-integration.sh

      - name: Display test outputs
        if: always()
        run: |
          echo "=== Integration Test Outputs ==="
          if [ -d "scripts/output" ]; then
            for file in scripts/output/*.txt; do
              if [ -f "$file" ]; then
                echo "=== $(basename "$file") ==="
                cat "$file"
                echo ""
              fi
            done
          fi
